defaultEntryPoints = ["https","http"]

logLevel = "ERROR"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false

[acme]
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"

[traefikLog]
  filePath = "/traefik_logs/traefik.log"
  format   = "json"

[accessLog]
  filePath = "/traefik_logs/access.log"
  format = "json"
